wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713147646.606998
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 95
      - 98
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.16.2
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
